remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages
  - _includes

title: Evan's Blog
github_username: CreatureOX
minimal_mistakes_skin: air
search: true
words_per_minute: 200

author:
  name: "Evan He"
  bio: "专注于C端、分布式"
  avatar: "/assets/images/avatar.jpg"      
  location: "Shanghai, CN"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

footer:
  links:
    - label: "GitHub"
      url: "https://github.com/CreatureOX"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false